name: turdes
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  common:
    path: ./modules/common
  core:
    path: ./modules/core
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter

  hydrated_bloc: ^9.1.5
  gen:
    path: ./modules/gen
  get_it: ^8.0.0

  google_fonts: ^6.2.1
  intl: ^0.19.0
  kartal: ^4.1.0
  logger: ^2.4.0
  vexana: ^5.0.1
  widgets:
    path: ./modules/widgets
  firebase_messaging: ^15.1.3
  shadcn_ui: ^0.13.4+1

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/translations/
